<a href="https://colab.research.google.com/github/MikhayahIV/faculdade-AI/blob/PythonDataScience/Exerc%C3%ADcios_Python_DataScience_VitorBlaia_A_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##IMPORTS

In [9]:
import numpy as np;
from scipy import stats;
np.random.seed(42);

## 1. Exercícios de NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100

In [6]:
# random implementa números aleatórios de um gerador(PNGs ou RNGs)
# randint() gera números interios aleatórios e nós passamos para comecar em 10 e ir até 100(101 não é incluído igual for etc)
# size determina que serão gerados 50 números
arr1 = np.random.randint(10, 101, size=50);
print(arr1);

[ 61  24  81  70  30  92  96  84  84  97  33  12  31  62  11  97  39  47
  11  73  69  30  42  85  67  31  98  58 100  68  51  69  89  24  71  71
  56  71  60  64  73  12  60  16  30  82  48  27  13  98]


2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha

In [7]:
# arange cria uma sequência
# no nosso caso ela começa em 1 e vai até 16(novamente o 17 não conta)
# reshape é para mudar o formato, no nosso caso vai transformar esses 16 números
# em uma matriz com 4 linhas e 4 colunas
mat2 = np.arange(1,17).reshape(4,4);
# o [-1,:] significa "Pegue a última linha de mat2 e todas as suas colunas"
# então ele vai na primeira coluna e pega o 13
# segunda coluna e pega o 14 etc
# 0,: = primeira linha
# :,0 = primeira coluna
# [linha,coluna] + :
ultima_linha = mat2[-1, :];
print("Matriz:\n",mat2);
print("Última linha:",ultima_linha);

Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Última linha: [13 14 15 16]


3. Crie um array de zeros com comprimento 15 e substitua os valores da 5 à 10 posição por 1

In [8]:
# zeros cria a array com zeros no lugar de números
# e aqui criamos com 15 POSIÇÕES
arr3 = np.zeros(15);
# aqui indica para começar no índice 4
# e parar antes do índice 10
# ÍNDICE E NÃO POSSIÇÃO
arr3[4:10] = 1;
print(arr3);

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [19]:
arr4 = np.random.randint(0,100, size=100);
# median calcula a mediana dos valores( da arr4 no caso)
mediana4 = np.median(arr4);
# e aqui o stats.mode() (do scipy) é utilizado para descobrir a moda
# keepdims=True é para manter a dimensão do resultado
# Então calcula a moda e mantém o formato do resultado de uma maneira que permite acessar
# ele encontra o mode e count
moda4 = stats.mode(arr4, keepdims=True);
print(arr4);
print("Media:", mediana4);

print("Moda:", moda4.mode[0], "- Frequência:", moda4.count[0])

[26 48 76 32 97 98  0 20 54  5 91 80 68 94  4  2 52 22 52 36 73 73 82 16
 84 77 72  0 50 44 76  3 61 64 31 33 91 94 71 38 25 33 53  2 49 11 64 53
  4 93 93 56 16 46 22 78 84 13 65 74 50 37 63 97 37 49 97 81 29 78 90 50
 62 97 51 37 96 87 78 29 50 80  4 28  3  9 55 16 73 16 83 87 68 33  5 52
 65 76 42 74]
Media: 52.5
Moda: 16 - Frequência: 4


5. Crie um aray de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3

In [21]:
arr5 = np.random.randint(1,101,size=20);
arr5_mod= arr5.copy();
arr5_mod[arr5_mod%3==0]=-3;
print("Original:",arr5);
print("Modificado:",arr5_mod);

Original: [23 55 80 95 75 16  8  4  4 56 25 67 96 67 27 93 32 50 61 51]
Modificado: [23 55 80 95 -3 16  8  4  4 56 25 67 -3 67 -3 -3 32 50 61 -3]


6. Gere uma matriz 5x5 de números aleatóios entre 0 e 1 e encontre a soma de cada coluna

In [22]:
# random.rand gera números aleatórios decimais entre 0 e 1(1 não é incluído. É aproximadamente)
# e depois passamos o formato da matriz 5x5
# no rand dois números indicam o formato
# no radint foi diferente (mínimo, limite máximo,
# formato(size=(5,5)) esse 5,5 dentro do size indica que sera uma matriz de 5x5)
# se fosse size(50) igual no primeiro exercico
# significa que vai gerar 50 números no caso
mat6 = np.random.rand(5,5);
# axis funciona como uma espécie de direcionamneto/eixo da operação
# 0 = vertical
# 1 = horizontal
# então vai pegar
soma_colunas6=mat6.sum(axis=0);
print("Matriz:\n",mat6);
print("Soma de cada coluna:", soma_colunas6)

Matriz:
 [[0.04086862 0.16893506 0.27859034 0.17701048 0.08870253]
 [0.12063587 0.46077877 0.20633372 0.36426986 0.50341727]
 [0.69039483 0.03931214 0.7994104  0.62790039 0.08175903]
 [0.87357862 0.9208724  0.06107796 0.27687765 0.80620128]
 [0.74825969 0.18452102 0.20934932 0.3704721  0.48452299]]
Soma de cada coluna: [2.47373763 1.77441939 1.55476174 1.81653049 1.9646031 ]


7. Crie dois arrays de números aleatórios e encotnre a correlação entre eles.

In [25]:
# O rand aqui apenas com 1 número
# significa que vai gerar 30 números aleatórios
a7 = np.random.rand(30);
b7 = np.random.rand(30);
# corrcoef() serve para calcular o coeficiente de correlação entre a e b7
# o np.corrcoef() devolve uma matriz
# então [0,1] significa linha 0 e coluna 1
correlacao7 = np.corrcoef(a7,b7)[0,1];
print("Correlação:",correlacao7)

Correlação: 0.2511402802781435


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado

In [26]:
mat8 = np.random.randint(1,10, size=(3,3));
mat8_quadrado = mat8 **2;
print("Matriz original:\n",mat8);
print("Matriz ao quadrado:\n",mat8_quadrado);

Matriz original:
 [[6 3 8]
 [9 6 7]
 [1 5 5]]
Matriz ao quadrado:
 [[36  9 64]
 [81 36 49]
 [ 1 25 25]]


9. Crie um array com 10 números aleatórios e normalize seus valores entre 0 e 1

In [30]:
arr9 = np.random.rand(10)*100;
norm9 = (arr9 - arr9.min()) / (arr9.max() - arr9.min());
print("Original:",arr9);
print("Normalizado:",norm9);

Original: [21.26807843 51.51736824 97.55413157 45.8988988  55.73053689 86.06320179
 53.50697189 18.44628714 29.95959118 30.99369263]
Normalizado: [0.03567018 0.41805059 1.         0.34702768 0.47130914 0.85474349
 0.44320111 0.         0.14553935 0.15861139]


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescente de 1 a 6

In [31]:
# eye() serve parrra criar uma matriz identidade
# ou seja, coloca 1 na diagonal principal e 0 no resto
mat10=np.eye(6);
# fill_diagonal() é para preencher na diagonal
# e vai começar no 1 até antes do 7
np.fill_diagonal(mat10,np.arange(1,7));
print(mat10);

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


11. Gere um array de 100 números inteiros e econtre o valor que mais se repete no array

In [33]:
arr11 = np.random.randint(0,20,size=100);
moda11 = stats.mode(arr11, keepdims=True);
print("Valor mais frequente:",moda11.mode[0], "- Frequência:",moda11.count[0]);

Valor mais frequente: 18 - Frequência: 10


12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7

In [38]:
mat12 = np.random.randint(1,10,size=(4,4));
# aqui o fill diagonal não tem o arange, então só vai colocar os 7
np.fill_diagonal(mat12,7);
print(mat12);

[[7 1 4 4]
 [3 7 4 1]
 [2 9 7 5]
 [9 9 8 7]]


13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa

In [39]:
arr13 = np.arange(2,21,2);
# cumsum = soma acumulada
# ou seja, vai percorrendo o array e somando o valor atual com tudo que veio antes
cumsum13=np.cumsum(arr13);
print("Pares:",arr13);
print("Soma cumulativa:", cumsum13);

Pares: [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: [  2   6  12  20  30  42  56  72  90 110]


14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.

In [43]:
a14= np.random.rand(10);
b14= np.random.rand(10);
diferenca14=a14-b14;
# mean() ele vai pegar todos os valores (nesse caso de diferenca14) e calcular
# a média aritmética
media_diferenca14=np.mean(diferenca14);
print("Diferenças:",diferenca14);
print("Média das diferenças:",media_diferenca14);

Diferenças: [ 0.41733162  0.82398154  0.32896267  0.42434608  0.51055999 -0.58051968
 -0.08621406 -0.01432349  0.84089057 -0.26634076]
Média das diferenças: 0.23986744792136974


15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50

In [44]:
arr15=np.random.randint(0,100,size=20);
arr15_mod=arr15.copy();
# [arr15_mod>50] verifica e pega todos os elementos que são maiores que 50
# e então atribua 50 (=50)
arr15_mod[arr15_mod>50]=50;
print("Original:",arr15);
print("Modificado:",arr15_mod);

Original: [83  4 64 93 48  2 44 13 29 67 17 61 36 24 47 64 52 78 72 14]
Modificado: [50  4 50 50 48  2 44 13 29 50 17 50 36 24 47 50 50 50 50 14]


16. Crie um array unidimensional e reorganize seus valoers em uma matriz 3x4

In [47]:
arr16=np.arange(12);
mat16=arr16.reshape(3,4);
print("Aray original:",arr16);
print("Matriz 3x4:\n",mat16);

Aray original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor po sua posição na matriz(índice linear, começando em 0)

In [48]:
mat17=np.random.randint(1,10,size=(4,4));
posicoes17=np.arange(mat17.size).reshape(4,4);
resultado17=mat17*posicoes17;
print("Matriz original:\n",mat17);
print("Posicoes:\n",posicoes17);
print("Resultado:\n",resultado17);

Matriz original:
 [[1 9 8 4]
 [5 5 6 7]
 [8 8 2 9]
 [7 4 4 8]]
Posicoes:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Resultado:
 [[  0   9  16  12]
 [ 20  25  36  49]
 [ 64  72  20  99]
 [ 84  52  56 120]]


18. Crie um array de 10 elementos contendo números entre 1 e 100 substitua todos os valores múltiplos de 5 por 0

In [50]:
arr18=np.random.randint(1,101,size=10);
arr18_mod=arr18.copy();
arr18_mod[arr18_mod%5==0]=0;
print("Original:",arr18);
print("Modificado:",arr18_mod);

Original: [ 6  5  5 54 47 87 49  9 99 20]
Modificado: [ 6  0  0 54 47 87 49  9 99  0]


19. Crie dois arrays de números interios aleatórios de tamanho 20 e calcule o ângulo entre eles(produto escalar normalizado)

In [60]:
a19=np.random.randint(1,10,size=20);
b19=np.random.randint(1,10,size=20);
# dot() serve para calcular o produto escalar
# linalg.norm() calcula o tamanho/comprimento
# com isso pegamos o cosseno do ângulo
cos_ang19=np.dot(a19,b19) / (np.linalg.norm(a19)*np.linalg.norm(b19));
# arccos é o cosseno inverso
# o arccos() é a função inversa do cosseno
# recebe o valor do cosseno e retorna o ângulo correspondete em radianos
# clip() vai garantir que o valor esteja entre -1 e 1
angulo_rad19=np.arccos(np.clip(cos_ang19,-1,1));
# então aqui temos o ângulo em radianos
print("Ângulo(radianos):",angulo_rad19);
# degrees() converte radianos para graus
print("Ângulo(graus):",np.degrees(angulo_rad19));

Ângulo(radianos): 0.6869267946987546
Ângulo(graus): 39.35800617068821


20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha

In [62]:
mat20=np.random.randint(0,50,size=(4,4));
min_linhas20=mat20.min(axis=1);
print("Matriz:\n",mat20);
print("Mínimo de cada linha:",min_linhas20);

Matriz:
 [[33 37 45  3]
 [37 18  5 33]
 [17 12 40 22]
 [18 44 10  0]]
Mínimo de cada linha: [ 3  5 12  0]
